title: Y. Yang
#description: 
author:
  name: Y. Yang
  email: yb.yang42@gmail.com


theme: minima


# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"
  
  social_links:
    github: y-yang42
    linkedin: yibo-yang
    rss: rss

# Minima: custom header links
header_pages:
  - _pages/index.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - Gemfile
    - Gemfile.lock
    - README.md
