title: Y. Yang
#description: 
author: "Y. Yang"


theme: minima

# Minima social links
github_username: y-yang42
linkedin_username: yibo-yang
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
#   - _pages/index.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - README.md
